---
- name: Init a new swarm with default parameters
  docker_swarm:
    state: present
    advertise_addr: 192.168.3.10

- name: Update swarm configuration
  docker_swarm:
    state: present
    election_tick: 5
