---
- name: Participate to swarm cluster
  docker_swarm:
    state: join
    advertise_addr: "{{ manager_ip }}"
    join_token: SWMTKN-1-4qyfv6zm0lc1uu5dald5bjoggo9bg3a0f36cj9douwmmg3sftg-5razfma8vabgj2qzc46vuirzl
    remote_addrs: ["{{ manager_ip }}:2377"]
  