---
- name: Participate to swarm cluster
  docker_swarm:
    state: join
    advertise_addr: "{{ manager_ip }}"
    join_token: "{{ hostvars['swarm-manager'].swarm.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: ["{{ manager_ip }}:2377"]
