---
- name: Deploy fuchain services on swarm
  hosts: swarm-manager
  tasks:
    - include_vars: variable.yml
    - name: Clone repository
      git:
        repo: "{{ app_repository }}"
        dest: "{{ app_directory }}"
        accept_hostkey: true
    - name: Deploy services
      shell:
        cmd: docker stack deploy -c docker-stack.yml librarian
        chdir: "{{ app_directory }}"
