---
  - name: Destroy fuchain services from swarm
    hosts: swarm-manager
    gather_facts: no
    tasks:
      - include_vars: variable.yml
      - name: Destroy services
        shell:
          cmd: docker stack rm librarian
          chdir: "{{ app_directory }}"
  