---
- name: Install packages
  hosts: all
  become: yes
  tasks:
    - include_vars: variable.yml
    - import_tasks: ./task/package_installation.yml

- name: Init swarm cluster
  hosts: swarm-manager
  become: yes
  tasks:
    - include_vars: variable.yml
    - import_tasks: ./task/swarm_initialization.yml

- name: Join cluster
  hosts: swarm-workers
  become: yes
  tasks:
    - include_vars: variable.yml
    - import_tasks: ./task/swarm_participation.yml
